### ISSUE TITLE
Passwords showing in console

### ISSUE THREAD

**Issue by thematheo** [lenis0012/LoginSecurity-2#161]
Hi, we've got cmd connected to discord private console chat room, and login command is showing with used password. Is there any way to prevent it from showing?

Thx for response. Cheers :)

**Comment by jagyCZ** [comment]
I have this problem too... Looks like developer is "very" active on github..

**Comment by lenis0012** [comment]
@thematheo @jagyCZ This has been fixed in v3.0.2

**Comment by thematheo** [comment]
Ok, thanks :)

**Comment by Lasdary** [comment]
> @thematheo @jagyCZ This has been fixed in v3.0.2

@lenis0012 ; I'm using 3.0.2 and I can still see the password onscreen; while it does not mirror on the logs or server console. Is this the expected behavior?
